/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Obsidian Kinetic design tokens — exact values from the source HTML
        'surface-container-low': '#1c1b1b',
        'surface-variant': '#353534',
        'surface-dim': '#131313',
        'on-secondary-fixed-variant': '#6a3b00',
        'on-tertiary-fixed': '#001d35',
        'primary-container': '#ff6b00',
        'on-secondary-fixed': '#2d1600',
        'tertiary-container': '#059eff',
        secondary: '#ffbc7c',
        'on-primary-container': '#572000',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#ffb874',
        'inverse-surface': '#e5e2e1',
        'surface-bright': '#3a3939',
        'on-surface': '#e5e2e1',
        'glow-orange': 'rgba(255, 107, 0, 0.15)',
        'surface-container': '#201f1f',
        'border-subtle': '#262626',
        'inverse-on-surface': '#313030',
        'on-tertiary-container': '#003357',
        'on-tertiary-fixed-variant': '#00497b',
        'on-secondary-container': '#633700',
        'primary-fixed': '#ffdbcc',
        'on-secondary': '#4b2800',
        'on-primary-fixed-variant': '#7a3000',
        'on-primary-fixed': '#351000',
        background: '#131313',
        'on-surface-variant': '#e2bfb0',
        'inverse-primary': '#a04100',
        'secondary-container': '#fe9400',
        'surface-container-high': '#2a2a2a',
        'outline-variant': '#5a4136',
        'surface-tint': '#ffb693',
        outline: '#a98a7d',
        'on-error': '#690005',
        error: '#ffb4ab',
        'text-primary': '#ffffff',
        primary: '#ffb693',
        'on-tertiary': '#003257',
        'text-muted': '#a3a3a3',
        'surface-container-highest': '#353534',
        tertiary: '#9ccaff',
        'secondary-fixed': '#ffdcbf',
        'tertiary-fixed': '#d0e4ff',
        'on-primary': '#561f00',
        'primary-fixed-dim': '#ffb693',
        surface: '#141414',
        'tertiary-fixed-dim': '#9ccaff',
        'on-background': '#e5e2e1',
        'error-container': '#93000a',
        'surface-container-lowest': '#0e0e0e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        'margin-mobile': '16px',
        xs: '4px',
        sm: '8px',
        'container-max': '1440px',
        xl: '48px',
        gutter: '20px',
        unit: '4px',
        lg: '24px',
      },
      fontFamily: {
        'body-md': ['Geist', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'code-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-mono': ['13px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '600' }],
        'code-sm': ['14px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
